# Generated by Django 4.1 on 2024-09-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="phone number"
            ),
        ),
    ]
