# Generated by Django 4.1 on 2024-08-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="auth_type",
            field=models.CharField(
                choices=[
                    ("GOOGLE", "Google Account"),
                    ("FACEBOOK", "Facebook Account"),
                    ("TELEGRAM", "Telegram Account"),
                    ("WITH EMAIL", "Email Account"),
                ],
                max_length=244,
                verbose_name="auth type",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram_id",
            field=models.CharField(max_length=55, verbose_name="telegram id"),
        ),
        migrations.AlterField(
            model_name="userotpcode",
            name="type",
            field=models.CharField(
                choices=[
                    ("register", "Register"),
                    ("reset_password", "Reset Password"),
                ],
                max_length=20,
                verbose_name="type",
            ),
        ),
    ]
