# Generated by Django 5.0.6 on 2024-08-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_user_phone_number_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_id",
            field=models.CharField(default=1, verbose_name="telegram id"),
            preserve_default=False,
        ),
    ]
