# Generated by Django 5.0.6 on 2024-08-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_user_device_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="device_id",
            field=models.CharField(
                blank=True,
                max_length=244,
                null=True,
                unique=True,
                verbose_name="device id",
            ),
        ),
    ]
