# Generated by Django 5.0.6 on 2024-08-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_socialuser_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_type",
            field=models.CharField(
                choices=[
                    ("GOOGLE", "Google Account"),
                    ("FACEBOOK", "Facebook Account"),
                    ("TELEGRAM", "Telegram Account"),
                    ("WITH EMAIL", "Email Account"),
                ],
                default=1,
                verbose_name="auth type",
            ),
            preserve_default=False,
        ),
    ]
