# Generated by Django 5.0.6 on 2024-08-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_user_auth_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=123, null=True),
        ),
    ]
