# Generated by Django 5.0.6 on 2024-07-26 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_alter_media_file"),
        ("news", "0006_rename_create_at_news_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="news",
                to="common.media",
            ),
        ),
    ]
