# Generated by Django 5.0.6 on 2024-08-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supject", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="click_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Click Count"
            ),
        ),
    ]
