# Generated by Django 5.1 on 2024-08-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supject", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubject",
            name="total_test_ball",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Total test ball"
            ),
        ),
    ]
