# Generated by Django 5.0.6 on 2024-09-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supject", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="description",
            field=models.TextField(default="initial club", verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="club",
            name="name",
            field=models.CharField(
                default="Club 1", max_length=100, verbose_name="Name"
            ),
        ),
    ]
