# Generated by Django 5.0.6 on 2024-08-12 16:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supject", "0002_rename_usertoteltestresult_usertotaltestresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubject",
            name="started_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
