# Generated by Django 5.0.6 on 2024-08-18 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supject", "0002_alter_club_users"),
    ]

    operations = []
