# Generated by Django 5.0 on 2024-08-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supject", "0002_alter_category_click_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="click_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Click Count"),
        ),
    ]
