# Generated by Django 5.0 on 2024-08-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supject", "0002_alter_category_click_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubject",
            name="finished",
            field=models.BooleanField(default=False),
        ),
    ]
