# Generated by Django 5.1 on 2024-08-17 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supject", "0003_alter_category_click_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubject",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_subjects",
                to="supject.subject",
                verbose_name="Subject",
            ),
        ),
    ]
