# Generated by Django 5.0.6 on 2024-08-12 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supject", "0004_alter_usersubject_total_test_ball"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="subject_title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="supject.subjecttitle",
                verbose_name="Subject title",
            ),
        ),
    ]
