# Generated by Django 5.0.6 on 2024-08-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supject", "0005_alter_subject_subject_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubject",
            name="started",
            field=models.BooleanField(default=False),
        ),
    ]
