# Generated by Django 5.0.6 on 2024-08-14 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supject", "0006_usersubject_started"),
    ]

    operations = [
        migrations.AlterField(
            model_name="step",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="supject.subject",
                verbose_name="Subject",
            ),
        ),
    ]
