# Generated by Django 5.0.6 on 2024-08-14 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_alter_media_file"),
        ("supject", "0007_alter_step_subject"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StepLesson",
            new_name="StepFile",
        ),
        migrations.AlterModelOptions(
            name="stepfile",
            options={
                "verbose_name": "Step's file",
                "verbose_name_plural": "Step's files",
            },
        ),
    ]
