# Generated by Django 5.0.6 on 2024-08-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supject", "0008_rename_steplesson_stepfile_alter_stepfile_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stepfile",
            name="title",
            field=models.CharField(max_length=250, verbose_name="title"),
        ),
    ]
