# Generated by Django 5.0.6 on 2024-08-14 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supject", "0009_alter_stepfile_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stepfile",
            name="step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="step_files",
                to="supject.step",
                verbose_name="Step",
            ),
        ),
        migrations.AlterField(
            model_name="steptest",
            name="step",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="supject.step",
                verbose_name="Step",
            ),
        ),
    ]
