# Generated by Django 5.0.6 on 2024-08-14 16:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supject", "0011_userstep"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userstep",
            unique_together={("user", "step")},
        ),
    ]
