# Generated by Django 5.0.6 on 2024-08-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supject", "0012_alter_userstep_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="testquestion",
            name="level",
            field=models.CharField(
                choices=[("easy", "easy"), ("medium", "medium"), ("hard", "hard")],
                default="easy",
                max_length=10,
            ),
        ),
    ]
