# Generated by Django 5.0.6 on 2024-08-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supject", "0013_testquestion_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="steptest",
            name="test_type",
            field=models.CharField(
                choices=[("midterm", "Midterm"), ("final", "Final")],
                max_length=30,
                verbose_name="Test type",
            ),
        ),
    ]
