# Generated by Django 5.0.6 on 2024-08-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supject", "0014_alter_steptest_test_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertotaltestresult",
            name="finished",
            field=models.BooleanField(default=False),
        ),
    ]
