# Generated by Django 5.0.6 on 2024-08-14 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supject", "0015_usertotaltestresult_finished"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testanswer",
            name="test_quetion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_answers",
                to="supject.testquestion",
                verbose_name="Question",
            ),
        ),
        migrations.AlterField(
            model_name="usertotaltestresult",
            name="ball",
            field=models.FloatField(blank=True, null=True, verbose_name="Bal"),
        ),
        migrations.AlterField(
            model_name="usertotaltestresult",
            name="correct_answers",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Count of correct answers"
            ),
        ),
    ]
