# Generated by Django 5.0.6 on 2024-08-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supject", "0016_alter_testanswer_test_quetion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstep",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
