# Generated by Django 5.0.6 on 2024-08-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supject", "0017_alter_userstep_finished_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertestresult",
            name="test_answer",
        ),
        migrations.AddField(
            model_name="usertestresult",
            name="test_answer",
            field=models.ManyToManyField(to="supject.testanswer"),
        ),
    ]
