# Generated by Django 5.0.6 on 2024-08-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supject", "0018_remove_usertestresult_test_answer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usertestresult",
            old_name="test_answer",
            new_name="test_answers",
        ),
    ]
