# Generated by Django 5.0.6 on 2024-08-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supject", "0019_rename_test_answer_usertestresult_test_answers"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertotaltestresult",
            name="percenateg",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
