# Generated by Django 5.0.6 on 2024-07-10 14:31

from django.db import migrations, models

import company.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=100)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=100,
                        validators=[company.validators.phone_number_validator],
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("location", models.URLField()),
            ],
            options={
                "verbose_name": "Contacts",
            },
        ),
    ]
