# Generated by Django 5.0.6 on 2024-07-10 14:49

import company.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.URLField(validators=[company.validators.validate_telegram_url])),
                ('facebook', models.URLField()),
                ('instagram', models.URLField(validators=[company.validators.validate_instagram_url])),
                ('linkedin', models.URLField()),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Medias',
            },
        ),
    ]
