# Generated by Django 5.0.6 on 2024-08-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="extra_data",
            field=models.JSONField(default=1, verbose_name="extra data"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notification",
            name="scheduled_date",
            field=models.DateTimeField(blank=True, verbose_name="scheduled date"),
        ),
    ]
