# Generated by Django 4.2.14 on 2024-08-16 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0006_aboutmistake_appinfo_contactwithuscategory_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faq",
            name="answer_en",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="answer_ru",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="answer_uz",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="question_en",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="question_ru",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="question_uz",
        ),
    ]
